# https://hub.docker.com/_/mysql
version: '3'

services:
  mysql:
    container_name: mysql_newbie
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: "newbie"
      MYSQL_PASSWORD: "newbie"
      MYSQL_DATABASE: "ssg"
    ports:
      - "3306:3306"
    command:
      - "mysqld"
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
# docker-compose up -d