### 주문 리스트 조회
GET {{host}}/api/external/orders

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### 주문 단일 조회
GET {{host}}/api/external/orders/{{orderId}}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### 주문 생성
POST {{host}}/api/external/orders
Content-Type: application/json

{
  "userId": 1,
  "productId": 1,
  "productCount": 10
}

> {%
client.global.set("orderId", response.body.toString())
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 200");
});
%}